export const PageContent = [
  {
    id: 0,
    name: `home-banner`,
    category: `home-page`,
    info: `none`,
    image: `../public/assets/images/hero-img-lg.jpg`,
  },
  {
    id: 1,
    name: `movie-banner`,
    category: `movie-page`,
    info: `none`,
    image: `../public/assets/images/movies-banner.jpg`,
  },
  {
    id: 2,
    name: `music-banner`,
    category: `music-page`,
    info: `none`,
    image: `../public/assets/images/music-banner.jpg`,
  },
  {
    id: 3,
    name: `tv-banner`,
    category: `tv-show-page`,
    info: `none`,
    image: `../public/assets/images/music-banner.jpg`,
  },
  {
    id: 4,
    name: `video-game-banner`,
    category: `video-game-page`,
    info: `none`,
    image: `../public/assets/images/videogame-banner.jpg`,
  },
  {
    id: 5,
    name: `home-page-header-logo`,
    category: `home-page`,
    info: `none`,
    image: `../public/assets/images/header-logo.png`,
  },
  {
    id: 6,
    name: `movie-page-header-logo`,
    category: `movie-page`,
    info: `none`,
    image: `../public/assets/images/know-movies.png`,
  },
  {
    id: 7,
    name: `music-page-header-logo`,
    category: `music-page`,
    info: `none`,
    image: `../public/assets/images/know-music.png`,
  },
  {
    id: 8,
    name: `tv-show-page-header-logo`,
    category: `tv-show-page`,
    info: `none`,
    image: `../public/assets/images/know-tv-shows.png`,
  },
  {
    id: 9,
    name: `video-game-page-header-logo`,
    category: `video-game-page`,
    info: `none`,
    image: `../public/assets/images/know-video-games.png`,
  },
  {
    id: 10,
    name: `anchorman`,
    category: `movie-page`,
    info: `none`,
    image: `../public/assets/images/movies-anchorman.jpg`,
  },
  {
    id: 11,
    name: `cloverfield`,
    category: `movie-page`,
    info: `none`,
    image: `../public/assets/images/movies-coverfield.jpg`,
  },
  {
    id: 10,
    name: `donnie-darko`,
    category: `movie-page`,
    info: `none`,
    image: `../public/assets/images/movies-donnie-darko.jpg`,
  },
];
