export const PageTopContent = [
  {
    id: 0,
    category: `home-about-page`,
    title: `hero image`,
    searchID: `none`,
    SearchPage: `none`,
    type: `none`,
    placeHolder: `none`,
    heroImage: `./assets/images/hero-img-lg.jpg`,
    pageTitleImage: `./assets/images/header-logo.png`,
  },
  {
    id: 1,
    category: `movie-page`,
    title: `hero image`,
    searchID: `title`,
    SearchPage: `Movies`,
    type: `movie`,
    placeHolder: `Search for a movie`,
    heroImage: `./assets/images/movies-banner.jpg`,
    pageTitleImage: `./assets/images/know-movies.png`,
  },
  {
    id: 2,
    category: `music-page`,
    title: `hero image`,
    searchID: `music-title`,
    SearchPage: `Music`,
    type: `music`,
    placeHolder: `Search song/artist`,
    heroImage: `./assets/images/music-banner.jpg`,
    pageTitleImage: `./assets/images/know-music.png`,
  },
  {
    id: 3,
    category: `tv-show-page`,
    title: `hero image`,
    searchID: `title`,
    SearchPage: `TV Shows`,
    type: `series`,
    placeHolder: `Search for a show`,
    heroImage: `./assets/images/tv-show-banner.jpg`,
    pageTitleImage: `./assets/images/know-tv-shows.png`,
  },
  {
    id: 4,
    category: `video-games-page`,
    title: `hero image`,
    searchID: `video-game-title`,
    SearchPage: `Video Games`,
    type: `video-game`,
    placeHolder: `Search for a game`,
    heroImage: `./assets/images/videogame-banner.jpg`,
    pageTitleImage: `./assets/images/know-video-games.png`,
  },
];
