export const PageContent = [
  {
    id: 0,
    name: `anchorman`,
    category: `movie-page`,
    title: `Anchorman`,
    info: ` Ron Burgundy is San Diego's top-rated newsman in the
    male-dominated broadcasting of the 1970s, but that's all about
    to change for Ron and his cronies when an ambitious woman is
    hired as a new anchor.`,
    trivia: `The film was inspired by a biography show that Will Ferrell watched about Jessica Savitch, and how one of her male co-workers confessed to being a total chauvinist back in the day.`,
    image: `./assets/images/movies-anchorman.jpg`,
  },
  {
    id: 1,
    name: `cloverfield`,
    category: `movie-page`,
    title: `Cloverfield`,
    info: ` A group of friends venture deep into the streets of New York on a rescue mission during a rampaging monster attack.`,
    trivia: `During the first weekend of the release, many theaters posted signs warning guests that the hand-held camera movements may cause motion sickness.`,
    image: `./assets/images/movies-cloverfield.jpg`,
  },
  {
    id: 2,
    name: `donnie-darko`,
    category: `movie-page`,
    title: `Donnie Darko`,
    info: ` After narrowly escaping a bizarre accident, a troubled teenager is plagued by visions of a man in a large rabbit suit who manipulates him to commit a series of crimes.`,
    trivia: `This was Seth Rogen’s feature film debut.`,
    image: `./assets/images/movies-donnie-darko.jpg`,
  },
  {
    id: 3,
    name: `bittersweet-symphony`,
    category: `music-page`,
    title: `Bittersweet Symphony`,
    info: `   Recorded by English rock band the Verve as the lead track on their third studio album, Urban Hymns (1997). The song was released on 16 June 1997 by Hut Recordings and Virgin Records as the first single from the album, reaching number two on the UK Singles Chart and remaining in the chart for three months.`,
    trivia: `The famous orchestral riff incorporates a sample from an obscure instrumental version of the 1965 Rolling Stones song ”The Last Time” by Stones producer Andrew Loog Oldham, who included it on a 1966 album called The Rolling Stones Songbook (credited to The Andrew Oldham Orchestra).`,
    image: `./assets/images/music-bittersweet-symphony.jpg`,
  },
  {
    id: 4,
    name: `teen-spirit`,
    category: `music-page`,
    title: `Smells Like Teen Spirit`,
    info: ` A song by American rock band Nirvana. It is the opening track and lead single from the band's second album, Nevermind (1991), released on DGC Records. The unexpected success of the song propelled Nevermind to the top of several albums charts at the start of 1992, an event often marked as the point when grunge entered the mainstream.`,
    trivia: `Kurt Cobain wrote this song for Nirvana; it came together in a jam session when he played it for the band. He said: "I was trying to write the ultimate pop song. I was basically trying to rip off The Pixies."`,
    image: `./assets/images/music-smells-like-teen-spirit.jpg`,
  },
  {
    id: 5,
    name: `cant-touch-this`,
    category: `music-page`,
    title: `U Can't Touch This`,
    info: ` A song co-written, produced and performed by MC Hammer from his 1990 album Please Hammer, Don't Hurt 'Em. It is considered to be his signature song.`,
    trivia: `The music is based on  “Super Freak” by Rick James. That song was a hit in 1981, so many younger listeners did not know the beat was sampled.`,
    image: `./assets/images/music-u-cant-touch-this.jpg`,
  },
  {
    id: 6,
    name: `dexter`,
    category: `tv-show-page`,
    title: `Dexter`,
    info: ` As a Miami forensics expert, he spends his days solving crimes, and nights committing them. But Dexter lives by a strict code of honor that is both his saving grace and lifelong burden. Torn between his deadly compulsion and his desire for true happiness, Dexter is a man in profound conflict with the world and himself.`,
    trivia: `Though they play brother and sister in the series, having met on the show, Michael C. Hall  and Jennifer Carpenter married on 31st December 2008. They subsequently divorced in December 2010, but continued to work together in the show.`,
    image: `./assets/images/tv-shows-dexter.jpg`,
  },
  {
    id: 7,
    name: `sopranos`,
    category: `tv-show-page`,
    title: `Sopranos`,
    info: ` An innovative look at the life of fictional Mafia Capo Tony Soprano, this serial is presented largely first person, but
    additional perspective is conveyed by the intimate conversations
    Tony has with his psychotherapist. We see Tony at work, at home,
    and in therapy.`,
    trivia: `James Gandolfini said that he was often contacted by real-life "wise guys", complimenting him on the authenticity of the series, as well as giving him advice.`,
    image: `./assets/images/tv-shows-sopranos.jpg`,
  },
  {
    id: 8,
    name: `south-park`,
    category: `tv-show-page`,
    title: `South Park`,
    info: `  The curious, adventure-seeking, fourth grade group of 10 year old boys, Stan, Kyle, Cartman, and Kenny, all join in in
    buffoonish adventures that sometimes evolve nothing. Sometimes
    something that was simple at the start, turns out to get out of
    control.`,
    trivia: `Most of Cartman's lines are ad-libbed by Trey Parker, who has stated that Cartman is his favorite character on the show.`,
    image: `./assets/images/tv-shows-south-park.jpeg`,
  },
  {
    id: 9,
    name: `god-of-war`,
    category: `video-games-page`,
    title: `God of War`,
    info: `Developed by Santa Monica Studio and published by Sony Computer Entertainment. First released on March 22, 2005, for the PlayStation 2 console.`,
    trivia: `David Jaffe's inspiration for the game was partly inspired by the 1981 film Clash of the Titans.`,
    image: `./assets/images/video-games-god-of-war.jpg`,
  },
  {
    id: 10,
    name: `half-life`,
    category: `video-games-page`,
    title: `Half-Life`,
    info: `Developed by Valve and published by Sierra Studios for Windows in 1998. It was Valve's debut product and the first game in the Half-Life series.`,
    trivia: `Half-Life was the highest-selling first-person shooter of all time up until the release of Call of Duty: Modern Warfare 3 (2011) - that's a total of 13 years`,
    image: `./assets/images/video-games-half-life.jpg`,
  },
  {
    id: 11,
    name: `mario-64`,
    category: `video-games-page`,
    title: `Mario 64`,
    info: `A 1996 platform game for the Nintendo 64 and the first Super Mario game to feature 3D gameplay. It was developed by Nintendo EAD and published by Nintendo.`,
    trivia: `Was voted as the most important video game ever by Electronic Gaming Magazine (Jan 2005).`,
    image: `./assets/images/video-games-mario-64.jpeg`,
  },
];
