export const PageTopContent = [
  {
    id: 0,
    name: `home-banner`,
    category: `home-about-page`,
    title: `hero image`,
    info: `none`,
    image: `../images/hero-img-lg.jpg`,
  },
  {
    id: 1,
    name: `movie-banner`,
    category: `movie-page`,
    title: `hero image`,
    info: `none`,
    image: `../images/movies-banner.jpg`,
  },
  {
    id: 2,
    name: `music-banner`,
    category: `music-page`,
    title: `hero image`,
    info: `none`,
    image: `../images/music-banner.jpg`,
  },
  {
    id: 3,
    name: `tv-banner`,
    category: `tv-show-page`,
    title: `hero image`,
    info: `none`,
    image: `../images/music-banner.jpg`,
  },
  {
    id: 4,
    name: `video-game-banner`,
    category: `video-games-page`,
    title: `hero image`,
    info: `none`,
    image: `../images/videogame-banner.jpg`,
  },
  {
    id: 5,
    name: `home-page-header-logo`,
    category: `home-about-page`,
    title: `page title image`,
    info: `none`,
    image: `../images/header-logo.png`,
  },
  {
    id: 6,
    name: `movie-page-header-logo`,
    category: `movie-page`,
    title: `page title image`,
    info: `none`,
    image: `../images/know-movies.png`,
  },
  {
    id: 7,
    name: `music-page-header-logo`,
    category: `music-page`,
    title: `page title image`,
    info: `none`,
    image: `../images/know-music.png`,
  },
  {
    id: 8,
    name: `tv-show-page-header-logo`,
    category: `tv-show-page`,
    title: `page title image`,
    info: `none`,
    image: `../images/know-tv-shows.png`,
  },
  {
    id: 9,
    name: `video-game-page-header-logo`,
    category: `video-games-page`,
    title: `page title image`,
    info: `none`,
    image: `../images/know-video-games.png`,
  },
];
