export const PageContent = [
  {
    id: 0,
    name: `home-banner`,
    category: `home-page`,
    info: `none`,
    image: `../images/hero-img-lg.jpg`,
  },
  {
    id: 1,
    name: `movie-banner`,
    category: `movie-page`,
    info: `none`,
    image: `../images/movies-banner.jpg`,
  },
  {
    id: 2,
    name: `music-banner`,
    category: `music-page`,
    info: `none`,
    image: `../images/music-banner.jpg`,
  },
  {
    id: 3,
    name: `tv-banner`,
    category: `tv-show-page`,
    info: `none`,
    image: `../images/music-banner.jpg`,
  },
  {
    id: 4,
    name: `video-game-banner`,
    category: `video-games-page`,
    info: `none`,
    image: `../images/videogame-banner.jpg`,
  },
  {
    id: 5,
    name: `home-page-header-logo`,
    category: `home-page`,
    info: `none`,
    image: `../images/header-logo.png`,
  },
  {
    id: 6,
    name: `movie-page-header-logo`,
    category: `movie-page`,
    info: `none`,
    image: `../images/know-movies.png`,
  },
  {
    id: 7,
    name: `music-page-header-logo`,
    category: `music-page`,
    info: `none`,
    image: `../images/know-music.png`,
  },
  {
    id: 8,
    name: `tv-show-page-header-logo`,
    category: `tv-show-page`,
    info: `none`,
    image: `../images/know-tv-shows.png`,
  },
  {
    id: 9,
    name: `video-game-page-header-logo`,
    category: `video-games-page`,
    info: `none`,
    image: `../images/know-video-games.png`,
  },
  {
    id: 10,
    name: `anchorman`,
    category: `movie-page`,
    info: `none`,
    image: `../images/movies-anchorman.jpg`,
  },
  {
    id: 11,
    name: `cloverfield`,
    category: `movie-page`,
    info: `none`,
    image: `../images/movies-coverfield.jpg`,
  },
  {
    id: 10,
    name: `donnie-darko`,
    category: `movie-page`,
    info: `none`,
    image: `../images/movies-donnie-darko.jpg`,
  },
  {
    id: 11,
    name: `bittersweet-symphony`,
    category: `music-page`,
    info: `none`,
    image: `../images/music-bittersweet-symphony.jpg`,
  },
  {
    id: 12,
    name: `teen-spirit`,
    category: `music-page`,
    info: `none`,
    image: `../images/music-smells-like-teen-spirit.jpg`,
  },
  {
    id: 13,
    name: `cant-touch-this`,
    category: `music-page`,
    info: `none`,
    image: `../images/music-u-cant-touch-this.jpg`,
  },
  {
    id: 14,
    name: `dexter`,
    category: `tv-show-page`,
    info: `none`,
    image: `../images/tv-shows-dexter.jpg`,
  },
  {
    id: 14,
    name: `sopranos`,
    category: `tv-show-page`,
    info: `none`,
    image: `../images/tv-shows-sapranos.jpg`,
  },
  {
    id: 15,
    name: `south-park`,
    category: `tv-show-page`,
    info: `none`,
    image: `../images/tv-shows-south-park.jpg`,
  },
  {
    id: 16,
    name: `god-of-war`,
    category: `video-games-page`,
    info: `none`,
    image: `../images/video-games-god-of-war.jpg`,
  },
  {
    id: 17,
    name: `half-life`,
    category: `video-games-page`,
    info: `none`,
    image: `../images/video-games-half-life.jpg`,
  },
  {
    id: 18,
    name: `mario-64`,
    category: `video-games-page`,
    info: `none`,
    image: `../images/video-games-mario-64.jpeg`,
  },
];
